<?php

declare(strict_types=1);

namespace Database\Factories;

use App\Models\Tenant;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<Tenant>
 */
class TenantFactory extends Factory
{
    public function definition(): array
    {
        // Slug is generated by the model on create to guarantee it matches the name and is unique.
        return [
            'name' => fake()->company().' Salon',
        ];
    }

    /**
     * Open Monday–Saturday with the given hours; closed on Sunday.
     */
    public function withStandardHours(string $opensAt = '09:00', string $closesAt = '21:00'): static
    {
        return $this->afterCreating(function (Tenant $tenant) use ($opensAt, $closesAt): void {
            foreach (range(1, 6) as $day) {
                $tenant->businessHours()->create([
                    'day_of_week' => $day,
                    'opens_at' => $opensAt,
                    'closes_at' => $closesAt,
                ]);
            }
        });
    }
}
